#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Pideck
#
#  This program is the main entry point.
#
# ---------------------------------------------------------------------------


# ----------------------------- CONFIG -------------------------------------

# where to search for music
#PLAYLISTS="-l /media/"

# the audio backend to use "alsa" or "jackd"
BACKEND="alsa"

#------------------------------------------------------------------------------

function get_timecode() {
   python /usr/share/pideck/timecode_select &
}

# kill everything first
killall --wait xwax
killall --wait jackd
killall --wait /usr/bin/jackd
killall --wait python
killall --wait lxpanel
echo "             "

#start card autodetection script
source /usr/share/pideck/cards_autodetect

#get type of timecode to use
TC_SELECT="$(get_timecode)"

#start crate scan script
source /usr/share/pideck/crate_scan_2

# start touchscreen buttons
python /usr/share/pideck/touchscreen_controls_L &
python /usr/share/pideck/touchscreen_controls_R &

sleep 1

if [ $BACKEND = "jackd" ]; then
    # start xwax
    if ( echo $TC_SELECT | grep -q "vinyl" ); then
    xwax -k -q 40 -g 630x480 --no-decor -j deck1 "${CRATES[@]}" &
    elif ( echo $TC_SELECT | grep -q "cd" ); then
    xwax -k -q 40 -g 630x480 --no-decor -t serato_cd -j deck1 "${CRATES[@]}" &
    else xwax -k -q 40 -g 630x480 --no-decor -j deck1 "${CRATES[@]}" &
    fi
    sleep 2

    # connect jack ports
    jack_connect system:capture_1 xwax:deck1_timecode_L
    jack_connect system:capture_2 xwax:deck1_timecode_R
    jack_connect system:playback_1 xwax:deck1_playback_L
    jack_connect system:playback_2 xwax:deck1_playback_R

else
    # start xwax
    if ( echo $TC_SELECT | grep -q "vinyl" ); then
     xwax -k -q 89 -g 630x480 --no-decor -m $BUFFER -r 48000 $XCARD "${CRATES[@]}" &
    elif ( echo $TC_SELECT | grep -q "cd" ); then
     xwax -k -q 89 -g 630x480 --no-decor -m $BUFFER -r 48000 -t serato_cd $XCARD "${CRATES[@]}" &
    else xwax -k -q 89 -g 630x480 --no-decor -m $BUFFER -r 48000 $XCARD "${CRATES[@]}" &
    fi
fi



