#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# RECording script
# 
# ---------------------------------------------------------------------------
# Config
#
# set path for recording
REC_PATH="/home/pi/recordings"
# 
# uncomment the following lines to use usbstick root for recording
#
# for NUM in 0 1 2 3 4 5 6 7; do
#   if [ -d "/media/usb$NUM" ]; then
#     if [ "$(ls -A "/media/usb$NUM")" ]; then
#      REC_PATH="/media/usb$NUM"
#     fi
#   fi
# done
#
# ---------------------------------------------------------------------------

# set ALSA as the recording mode for sox
export AUDIODRIVER=alsa

# set a large input buffer to avoid recording glitches
export SOX_OPTS="--input-buffer 64000"

# parse soundcard file
CARDS_LINE_1=`sed '1,2!d' /proc/asound/cards`
CARDS_LINE_2=`sed '3,4!d' /proc/asound/cards`

echo "        "
echo "Available sound cards : "
echo $CARDS_LINE_1
echo $CARDS_LINE_2 
echo "        "

#check if there is just one card to kill xwax
if test -z "$CARDS_LINE_2"; then

   echo " killing xwax to start recording"
   echo "           "
    killall --wait xwax
    killall --wait jackd
    killall --wait /usr/bin/jackd
    killall --wait lxpanel
    echo "             "
    
    CARD_NUM=`echo $CARDS_LINE_1 | grep -o "[0-9]" | head -1`
    RCARD=hw:$CARD_NUM

    export AUDIODEV=$RCARD
    echo "recording with: "$RCARD
    if [ -d "$REC_PATH" ]; then lxterminal --command="rec -r 44100 -b 16 -c 2 $(date +"%Y-%m-%d_%H-%M-%S").flac" --geometry=70x30 --working-directory="$REC_PATH"
    else
        mkdir $REC_PATH
        lxterminal --command="rec -r 44100 -b 16 -c 2 $(date +"%Y-%m-%d_%H-%M-%S").flac" --geometry=70x30 --working-directory="$REC_PATH"
    fi
    
    exit

else

 # if 2 cards present check for supported cards.
 
source /usr/share/pideck/cards_autodetect
export AUDIODEV=$RCARD
echo "recording with: "$RCARD

 if [ -d "$REC_PATH" ]; then lxterminal --command="rec -r 44100 -b 16 -c 2 $(date +"%Y-%m-%d_%H-%M-%S").flac" --geometry=70x30 --working-directory="$REC_PATH"
 else
   mkdir $REC_PATH
   lxterminal --command="rec -r 44100 -b 16 -c 2 $(date +"%Y-%m-%d_%H-%M-%S").flac" --geometry=70x30 --working-directory="$REC_PATH"
 fi

fi
