#!/usr/bin/env python
# ---------------------------------------------------------------------------
# Touchscreen controller
#
#  This program emulates keyboard key presses using a touchscreen.
#
# ---------------------------------------------------------------------------

import pygtk
pygtk.require('2.0')
import gtk
import time
import sys
import os
import argparse

from Xlib.X import NONE
from Xlib.XK import string_to_keysym
from Xlib.display import Display
from Xlib.protocol import event

parser = argparse.ArgumentParser()

parser.add_argument('--version', action='version',
                    version='%(prog)s 0.2')

parser.add_argument('--card', action='store',
                    dest='card',
                    help='set the soundcard in use')

results = parser.parse_args()
print('Right buttons: soundcard is set to = {!r}'.format(results.card))

def fake_press_key(key_to_press):

    os.system("wmctrl -a xwax")
    display = Display()
    focus_window = display.get_input_focus().focus
    keycode = display.keysym_to_keycode(string_to_keysym(key_to_press))

    key_event = event.KeyPress(
            time=int(time.time()),
            root=display.screen().root,
            window=focus_window,
            same_screen=0, child=NONE,
            root_x=0, root_y=0, event_x=0, event_y=0,
            state=0,
            detail=keycode
    )

    focus_window.send_event(key_event)

    display.sync()


def fake_release_key(key_to_press):

    os.system("wmctrl -a xwax")
    display = Display()
    focus_window = display.get_input_focus().focus
    keycode = display.keysym_to_keycode(string_to_keysym(key_to_press))


    key_event = event.KeyRelease(
            time=int(time.time()),
            root=display.screen().root,
            window=focus_window,
            same_screen=0, child=NONE,
            root_x=0, root_y=0, event_x=0, event_y=0,
            state=0,
            detail=keycode
    )

    focus_window.send_event(key_event)

    display.sync()

    os.system("wmctrl -a touchscreen")

def load_button(event):
    fake_press_key("F5")
    fake_release_key("F5")

def cue_button(event):
    fake_press_key("F6")
    fake_release_key("F6")

def timecode_button(event):
    fake_press_key("F7")
    fake_release_key("F7")

def traktora6_phono_button(widget, data):
    if widget.get_active():
       os.system("amixer -c T6 cset numid=4 on")
    else:
       os.system("amixer -c T6 cset numid=4 off")

def traktora6_bypass_button(widget, data):
    if widget.get_active():
       os.system("amixer -c T6 cset numid=2 on")
    else:
       os.system("amixer -c T6 cset numid=2 off")

def up_button(event):
    fake_press_key("Up")
    fake_release_key("Up")

def pageup_button(event):
    fake_press_key("Page_Up")
    fake_release_key("Page_Up")

def down_button(event):
    fake_press_key("Down")
    fake_release_key("Down")

def pagedown_button(event):
    fake_press_key("Page_Down")
    fake_release_key("Page_Down")

def sort_button(event):
    fake_press_key("Shift_L")
    fake_release_key("Shift_L")

def rescan_button(event):
    fake_press_key("Right")
    fake_press_key("Control_L")
    fake_release_key("Right")
    fake_release_key("Control_L")

def on_key_press_event(widget, event):
    keyname = gtk.gdk.keyval_name(event.keyval)
    if keyname == "F10":
        os.system("lxterminal &")

def make_window():
    win = gtk.Window()
    win.set_title("Touchscreen Controls2")
    win.set_decorated(False)
    win.set_default_size(50, 480)
    win.move(725, 0)
    win.add_events(gtk.gdk.KEY_PRESS_MASK)
    win.connect("key-press-event", on_key_press_event)
    win.connect("destroy", gtk.main_quit)

    box = gtk.VButtonBox()

    if results.card == 'traktora6' or results.card == 'twindeck' or results.card == 'ranesl1':
        btn = gtk.Button("LOAD")
        btn.connect("clicked", load_button)
        btn.set_size_request(50, 68)
        box.add(btn)

        btn = gtk.Button("CUE")
        btn.connect("clicked", cue_button)
        btn.set_size_request(50, 68)
        box.add(btn)

        btn = gtk.Button("TIMECD")
        btn.connect("clicked", timecode_button)
        btn.set_size_request(50, 68)
        box.add(btn)

    if results.card == 'traktora6':
        btn = gtk.ToggleButton("PHONO")
        map = btn.get_colormap()
        color = map.alloc_color("green")
        style = btn.get_style().copy()
        style.bg[gtk.STATE_ACTIVE] = color
        btn.set_style(style)
        btn.connect("toggled", traktora6_phono_button,"PHONO")
        btn.set_size_request(50, 68)
        box.add(btn)

        btn = gtk.ToggleButton("BYPASS")
        map = btn.get_colormap()
        color = map.alloc_color("red")
        style = btn.get_style().copy()
        style.bg[gtk.STATE_ACTIVE] = color
        btn.set_style(style)
        btn.connect("toggled", traktora6_bypass_button,"BYPASS")
        btn.set_size_request(50, 68)
        box.add(btn)

    btn = gtk.Button("PG UP")
    btn.connect("clicked", pageup_button)
    btn.set_size_request(50, 68)
    box.add(btn)

    btn = gtk.Button("UP")
    btn.connect("clicked", up_button)
    btn.set_size_request(50, 68)
    box.add(btn)

    btn = gtk.Button("DOWN")
    btn.connect("clicked", down_button)
    btn.set_size_request(50, 68)
    box.add(btn)

    btn = gtk.Button("PG DOWN")
    btn.connect("clicked", pagedown_button)
    box.add(btn)

    if results.card != 'traktora6' and results.card != 'twindeck':
        btn = gtk.Button("SORT")
        btn.connect("clicked", sort_button)
        btn.set_size_request(50, 68)
        box.add(btn)

        btn = gtk.Button("RESCAN")
        btn.connect("clicked", rescan_button)
        btn.set_size_request(50, 68)
        box.add(btn)

    win.add(box)

    win.show_all()

    gtk.main()

display = Display()
make_window()
