#!/usr/bin/env python
#
# Python XWax Touchscreen controller
#
# sudo apt-get install psmisc python-gtk2 python-xlib wmctrl
#

import pygtk
pygtk.require('2.0')
import gtk
import time
import sys
import os

from Xlib.X import NONE
from Xlib.XK import string_to_keysym
from Xlib.display import Display
#from Xlib.ext import xinput
from Xlib.protocol import event

def fake_press_key(dunno, key_to_press):
	os.system("wmctrl -a xwax")
	display = Display()
	#screen = display.screen()
	focus_window = display.get_input_focus().focus
	keycode = display.keysym_to_keycode(string_to_keysym(key_to_press))

	key_event = event.KeyPress(
	        time=int(time.time()),
	        root=display.screen().root,
	        window=focus_window,
	        same_screen=0, child=NONE,
	        root_x=0, root_y=0, event_x=0, event_y=0,
	        state=0,
        	detail=keycode
	)

	focus_window.send_event(key_event)
	key_event = event.KeyRelease(
	        time=int(time.time()),
	        root=display.screen().root,
	        window=focus_window,
	        same_screen=0, child=NONE,
	        root_x=0, root_y=0, event_x=0, event_y=0,
	        state=0,
        	detail=keycode
	)

	focus_window.send_event(key_event)

	display.sync()

	os.system("wmctrl -a touchscreen")


def make_window():
	win = gtk.Window()
	win.set_title("Touchscreen Controls")
	win.set_decorated(False)
	win.set_default_size(800, 50)
	win.move(0, 0)
	win.connect("destroy", gtk.main_quit)

	box = gtk.HButtonBox()

	btn = gtk.Button("LOAD")
	btn.connect("clicked", fake_press_key, "F1")
	btn.set_size_request(120, 50)
	box.add(btn)

	btn = gtk.Button("CUE1")
	btn.connect("clicked", fake_press_key, "F2")
	box.add(btn)

	btn = gtk.Button("TIMECODE")
	btn.connect("clicked", fake_press_key, "F3")
	box.add(btn)

	btn = gtk.Button("UP")
	btn.connect("clicked", fake_press_key, "Up")
	box.add(btn)

	btn = gtk.Button("DOWN")
	btn.connect("clicked", fake_press_key, "Down")
	box.add(btn)

	win.add(box)

	win.show_all()

	gtk.main()

display = Display()

make_window()
