#!/usr/bin/env python
# ---------------------------------------------------------------------------
# Touchscreen controller
#
#  This program emulates keyboard key presses using a touchscreen.
#
# ---------------------------------------------------------------------------

import pygtk
pygtk.require('2.0')
import gtk
import time
import sys
import os

from Xlib.X import NONE
from Xlib.XK import string_to_keysym
from Xlib.display import Display
#from Xlib.ext import xinput
from Xlib.protocol import event


def fake_press_key(key_to_press):
    os.system("wmctrl -a xwax")
    display = Display()
    #screen = display.screen()
    focus_window = display.get_input_focus().focus
    keycode = display.keysym_to_keycode(string_to_keysym(key_to_press))

    key_event = event.KeyPress(
            time=int(time.time()),
            root=display.screen().root,
            window=focus_window,
            same_screen=0, child=NONE,
            root_x=0, root_y=0, event_x=0, event_y=0,
            state=0,
            detail=keycode
    )

    focus_window.send_event(key_event)
    key_event = event.KeyRelease(
            time=int(time.time()),
            root=display.screen().root,
            window=focus_window,
            same_screen=0, child=NONE,
            root_x=0, root_y=0, event_x=0, event_y=0,
            state=0,
            detail=keycode
    )

    focus_window.send_event(key_event)

    display.sync()

    os.system("wmctrl -a touchscreen")


fake_press_key("Right")
fake_press_key("Control_L")
