#!/bin/sh

# don't autostart the software
# TODO: this relies on the username being pi, and their home dir being in the standard place
if [ -L /home/pi/.config/autostart/pideck.desktop ] ; then
    rm /home/pi/.config/autostart/pideck.desktop
fi

# reload the udev rules
udevadm control --reload-rules

# remove the USB mounting directories
mkdir /media 2> /dev/null || :
for i in 0 1 2 3 4 5 6 7; do
    rmdir /media/usb$i 2> /dev/null || :
done

# the script will always succeed
exit 0
